### PR TITLE
First pass - v9 update + some other RE doc things

### PR DESCRIPTION
**Pull request by KazWolfe**

### CODE REVIEW

**Comment by philpax** [comment]
what's the go on this

**Review by philpax — APPROVED** [review]
looks good but you might want to sprinkle in some of those lint disables to get rid of the warnings from the stupid rules

**Comment by KazWolfe** [comment]
Honestly I'd just globally suppress that rule, because that rule is stupid. Unfortunately, remark doesn't seem to have any docs on how to do this, yay JS ecosystem.

**Comment by philpax** [comment]
Ok #20 and #21 should fix that, feel free to update and merge at your convenience

**Comment by philpax** [comment]
Checking on this

**Pull request merged**
